#define MAXX				1100
#define MAXY				750
#define MAXSIZE				11
#define M_PI				3.1415926535897932384626433832795 
#define R					20
#define min(a, b)			(((a) < (b)) ? (a) : (b))
#define oo					0x3c3c3c3c

#define KHUNGVE_LEFT		MAXX/2 - 200
#define KHUNGVE_RIGHT		MAXX
#define KHUNGVE_TOP			30
#define KHUNGVE_BOTTOM		MAXY - 250

#define BTN_VEDINH_LEFT		KHUNGVE_LEFT + 1
#define BTN_VEDINH_TOP		KHUNGVE_TOP + 1
#define BTN_VEDINH_RIGHT	BTN_VEDINH_LEFT + 50
#define BTN_VEDINH_BOTTOM	BTN_VEDINH_TOP + 50

#define BTN_VECANH_LEFT		KHUNGVE_LEFT + 1
#define BTN_VECANH_TOP		KHUNGVE_TOP + 51
#define BTN_VECANH_RIGHT	BTN_VECANH_LEFT + 50
#define BTN_VECANH_BOTTOM	BTN_VECANH_TOP + 50

#define BTN_XOADINH_LEFT	KHUNGVE_LEFT + 1
#define BTN_XOADINH_TOP		KHUNGVE_TOP + 101
#define BTN_XOADINH_RIGHT	BTN_XOADINH_LEFT + 50
#define BTN_XOADINH_BOTTOM	BTN_XOADINH_TOP + 50

#define BTN_DICHUYEN_LEFT	KHUNGVE_LEFT + 1
#define BTN_DICHUYEN_TOP	KHUNGVE_TOP + 151
#define BTN_DICHUYEN_RIGHT	BTN_DICHUYEN_LEFT + 50
#define BTN_DICHUYEN_BOTTOM	BTN_DICHUYEN_TOP + 50

#define BTN_SAVEFILE_LEFT	KHUNGVE_LEFT + 1
#define BTN_SAVEFILE_TOP	KHUNGVE_TOP + 201
#define BTN_SAVEFILE_RIGHT	BTN_SAVEFILE_LEFT + 50
#define	BTN_SAVEFILE_BOTTOM	BTN_SAVEFILE_TOP + 50

#define BTN_LOADFILE_LEFT	KHUNGVE_LEFT + 1
#define BTN_LOADFILE_TOP	KHUNGVE_TOP + 251
#define BTN_LOADFILE_RIGHT	BTN_LOADFILE_LEFT + 50
#define	BTN_LOADFILE_BOTTOM	BTN_LOADFILE_TOP + 50

#define BTN_CLEANALL_LEFT	KHUNGVE_LEFT + 1
#define BTN_CLEANALL_TOP	KHUNGVE_TOP + 301
#define BTN_CLEANALL_RIGHT	BTN_CLEANALL_LEFT  + 50
#define BTN_CLEANALL_BOTTOM	BTN_CLEANALL_TOP + 50

#define BTN_BFS_LEFT		20
#define BTN_BFS_TOP			45
#define BTN_BFS_RIGHT		BTN_BFS_LEFT + 80
#define BTN_BFS_BOTTOM		BTN_BFS_TOP + 40

#define BTN_DFS_LEFT		BTN_BFS_RIGHT + 25
#define BTN_DFS_TOP			BTN_BFS_TOP
#define BTN_DFS_RIGHT		BTN_DFS_LEFT	+ 80
#define BTN_DFS_BOTTOM		BTN_DFS_TOP + 40

#define BTN_TIMTCDDI_LEFT	20
#define BTN_TIMTCDDI_TOP	BTN_BFS_BOTTOM + 15
#define BTN_TIMTCDDI_RIGHT	BTN_TIMTCDDI_LEFT + 80
#define BTN_TIMTCDDI_BOTTOM	BTN_TIMTCDDI_TOP + 40

#define BTN_SCC_LEFT		BTN_DFS_RIGHT + 25
#define BTN_SCC_TOP			BTN_DFS_TOP
#define BTN_SCC_RIGHT		BTN_SCC_LEFT + 80
#define BTN_SCC_BOTTOM		BTN_SCC_TOP + 40

#define	BTN_TIMTRU_LEFT		BTN_TIMTCDDI_RIGHT + 25
#define BTN_TIMTRU_TOP		BTN_TIMTCDDI_TOP
#define BTN_TIMTRU_RIGHT	BTN_TIMTRU_LEFT + 80
#define BTN_TIMTRU_BOTTOM	BTN_TIMTRU_TOP + 40

#define BTN_CANHCAU_LEFT	BTN_TIMTRU_RIGHT + 25
#define BTN_CANHCAU_TOP		BTN_TIMTRU_TOP
#define BTN_CANHCAU_RIGHT	BTN_CANHCAU_LEFT + 80
#define BTN_CANHCAU_BOTTOM	BTN_CANHCAU_TOP + 40

#define BTN_EULER_LEFT		20
#define BTN_EULER_TOP		BTN_TIMTCDDI_BOTTOM + 15
#define BTN_EULER_RIGHT		BTN_EULER_LEFT + 80
#define BTN_EULER_BOTTOM	BTN_EULER_TOP + 40

#define BTN_HAMILTON_LEFT	BTN_EULER_RIGHT + 25
#define BTN_HAMILTON_TOP	BTN_EULER_TOP
#define BTN_HAMILTON_RIGHT	BTN_HAMILTON_LEFT + 80
#define BTN_HAMILTON_BOTTOM	BTN_HAMILTON_TOP + 40

#define BTN_DIJKSTRA_LEFT	BTN_HAMILTON_RIGHT + 25
#define BTN_DIJKSTRA_TOP	BTN_HAMILTON_TOP
#define BTN_DIJKSTRA_RIGHT	BTN_DIJKSTRA_LEFT + 80
#define BTN_DIJKSTRA_BOTTOM	BTN_DIJKSTRA_TOP + 40

#define MTK_LEFT			15
#define MTK_TOP				BTN_DIJKSTRA_BOTTOM + 40
#define MTK_RIGHT			KHUNGVE_LEFT - 35
#define MTK_BOTTOM			MTK_TOP + 20

#define HELP_LEFT			0
#define HELP_TOP			MAXY - 40
#define HELP_RIGHT			MAXX
#define HELP_BOTTOM			MAXY

#define LOG_LEFT			0
#define LOG_TOP				KHUNGVE_BOTTOM + 20
#define LOG_RIGHT			MAXX
#define LOG_BOTTOM			HELP_TOP - 10

enum LUACHON{NON, VE_DINH, VE_CANH, XOA_DINH, DI_CHUYEN, SAVE_FILE, LOAD_FILE, CLEAN,
	DUYET_BFS, DUYET_DFS, ALL_PATH, FIND_SCC, DIJKSTRA_ALG, TIM_TRU, TIM_CCAU, EULER, HAMILTON};